POST http://localhost:8082/blogs/new
Content-Type: application/json

{
    "title": "Darjeeling", 
    "authors": ["Jane Doe","Elf Wick"],
    "content": "", 
    "publishedAt": null
}

###
GET http://localhost:8082/blogs

###
GET http://localhost:8082/blogs/676c34ac90ce309efa380413

###
PATCH http://localhost:8082/blogs/676c34ac90ce309efa380413
Content-Type: application/json

{
    "content": "Darjeeling is famous for its tea."
}

###
DELETE http://localhost:8082/blogs/676c34ac90ce309efa380413